# Generated by Django 5.2 on 2025-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='銘柄')),
                ('brewery', models.CharField(blank=True, max_length=200, verbose_name='酒蔵')),
                ('score', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3, verbose_name='評価')),
                ('tasting_date', models.DateField(verbose_name='飲んだ日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='ラベル画像')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
