# Generated by Django 5.2 on 2025-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sake_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake',
            name='fetched_image_url',
            field=models.URLField(blank=True, verbose_name='取得した画像URL'),
        ),
        migrations.AddField(
            model_name='sake',
            name='refference_url',
            field=models.URLField(blank=True, verbose_name='参考URL'),
        ),
    ]
