# Generated by Django 5.2 on 2025-12-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_note', '0002_sake_fetched_image_url_sake_refference_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sake',
            name='fetched_image_url',
        ),
        migrations.RemoveField(
            model_name='sake',
            name='refference_url',
        ),
    ]
