# Generated by Django 5.2 on 2025-12-19 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sake_note', '0004_sake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake',
            name='acidity',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='酸味'),
        ),
        migrations.AddField(
            model_name='sake',
            name='aftertaste',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='後味'),
        ),
        migrations.AddField(
            model_name='sake',
            name='aroma',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='香り'),
        ),
        migrations.AddField(
            model_name='sake',
            name='sweetness',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='甘み'),
        ),
        migrations.AddField(
            model_name='sake',
            name='umami',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='旨味'),
        ),
    ]
